import requests, json

d = {
  "action": "opened",
  "issue": {
    "url": "https://api.github.com/repos/sorryGithub/public-repo/issues/2",
    "labels_url": "https://api.github.com/repos/sorryGithub/public-repo/issues/2/labels{/name}",
    "comments_url": "https://api.github.com/repos/sorryGithub/public-repo/issues/2/comments",
    "events_url": "https://api.github.com/repos/sorryGithub/public-repo/issues/2/events",
    "html_url": "https://github.com/sorryGithub/public-repo/issues/2",
    "id": 73464126,
    "number": 2,
    "title": "Spelling error in the README file",
    "user": {
      "login": "sorryGithub",
      "id": 6752317,
      "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sorryGithub",
      "html_url": "https://github.com/sorryGithub",
      "followers_url": "https://api.github.com/users/sorryGithub/followers",
      "following_url": "https://api.github.com/users/sorryGithub/following{/other_user}",
      "gists_url": "https://api.github.com/users/sorryGithub/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sorryGithub/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sorryGithub/subscriptions",
      "organizations_url": "https://api.github.com/users/sorryGithub/orgs",
      "repos_url": "https://api.github.com/users/sorryGithub/repos",
      "events_url": "https://api.github.com/users/sorryGithub/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sorryGithub/received_events",
      "type": "User",
      "site_admin": False
    },
    "labels": [
      {
        "id": 208045946,
        "url": "https://api.github.com/repos/sorryGithub/public-repo/labels/bug",
        "name": "bug",
        "color": "fc2929",
        "default": True
      }
    ],
    "state": "open",
    "locked": False,
    "assignee": None,
    "milestone": None,
    "comments": 0,
    "created_at": "2015-05-05T23:40:28Z",
    "updated_at": "2015-05-05T23:40:28Z",
    "closed_at": None,
    "body": "It looks like you accidently spelled 'commit' with two 't's."
  },
  "repository": {
    "id": 35129377,
    "name": "public-repo",
    "full_name": "sorryGithub/public-repo",
    "owner": {
      "login": "sorryGithub",
      "id": 6752317,
      "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sorryGithub",
      "html_url": "https://github.com/sorryGithub",
      "followers_url": "https://api.github.com/users/sorryGithub/followers",
      "following_url": "https://api.github.com/users/sorryGithub/following{/other_user}",
      "gists_url": "https://api.github.com/users/sorryGithub/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sorryGithub/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sorryGithub/subscriptions",
      "organizations_url": "https://api.github.com/users/sorryGithub/orgs",
      "repos_url": "https://api.github.com/users/sorryGithub/repos",
      "events_url": "https://api.github.com/users/sorryGithub/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sorryGithub/received_events",
      "type": "User",
      "site_admin": False
    },
    "private": False,
    "html_url": "https://github.com/sorryGithub/public-repo",
    "description": "",
    "fork": False,
    "url": "https://api.github.com/repos/sorryGithub/public-repo",
    "forks_url": "https://api.github.com/repos/sorryGithub/public-repo/forks",
    "keys_url": "https://api.github.com/repos/sorryGithub/public-repo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sorryGithub/public-repo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sorryGithub/public-repo/teams",
    "hooks_url": "https://api.github.com/repos/sorryGithub/public-repo/hooks",
    "issue_events_url": "https://api.github.com/repos/sorryGithub/public-repo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sorryGithub/public-repo/events",
    "assignees_url": "https://api.github.com/repos/sorryGithub/public-repo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sorryGithub/public-repo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sorryGithub/public-repo/tags",
    "blobs_url": "https://api.github.com/repos/sorryGithub/public-repo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sorryGithub/public-repo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sorryGithub/public-repo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sorryGithub/public-repo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sorryGithub/public-repo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sorryGithub/public-repo/languages",
    "stargazers_url": "https://api.github.com/repos/sorryGithub/public-repo/stargazers",
    "contributors_url": "https://api.github.com/repos/sorryGithub/public-repo/contributors",
    "subscribers_url": "https://api.github.com/repos/sorryGithub/public-repo/subscribers",
    "subscription_url": "https://api.github.com/repos/sorryGithub/public-repo/subscription",
    "commits_url": "https://api.github.com/repos/sorryGithub/public-repo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sorryGithub/public-repo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sorryGithub/public-repo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sorryGithub/public-repo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sorryGithub/public-repo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sorryGithub/public-repo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sorryGithub/public-repo/merges",
    "archive_url": "https://api.github.com/repos/sorryGithub/public-repo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sorryGithub/public-repo/downloads",
    "issues_url": "https://api.github.com/repos/sorryGithub/public-repo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sorryGithub/public-repo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sorryGithub/public-repo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sorryGithub/public-repo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sorryGithub/public-repo/labels{/name}",
    "releases_url": "https://api.github.com/repos/sorryGithub/public-repo/releases{/id}",
    "created_at": "2015-05-05T23:40:12Z",
    "updated_at": "2015-05-05T23:40:12Z",
    "pushed_at": "2015-05-05T23:40:27Z",
    "git_url": "git://github.com/sorryGithub/public-repo.git",
    "ssh_url": "git@github.com:sorryGithub/public-repo.git",
    "clone_url": "https://github.com/sorryGithub/public-repo.git",
    "svn_url": "https://github.com/sorryGithub/public-repo",
    "homepage": None,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": None,
    "has_issues": True,
    "has_downloads": True,
    "has_wiki": True,
    "has_pages": True,
    "forks_count": 0,
    "mirror_url": None,
    "open_issues_count": 2,
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "sorryGithub",
    "id": 6752317,
    "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sorryGithub",
    "html_url": "https://github.com/sorryGithub",
    "followers_url": "https://api.github.com/users/sorryGithub/followers",
    "following_url": "https://api.github.com/users/sorryGithub/following{/other_user}",
    "gists_url": "https://api.github.com/users/sorryGithub/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sorryGithub/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sorryGithub/subscriptions",
    "organizations_url": "https://api.github.com/users/sorryGithub/orgs",
    "repos_url": "https://api.github.com/users/sorryGithub/repos",
    "events_url": "https://api.github.com/users/sorryGithub/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sorryGithub/received_events",
    "type": "User",
    "site_admin": False
  }
}

x = {"payload" : json.dumps(d)}

requests.post("http://127.0.0.1:8080/connector/github",data=x)